import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("bg-linear-to-r from-[#ffffff]", "font-sans", geist.variable)}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        <div className="pt-20">{children}</div>
      </body>
    </html>
  );
}
